### ISSUE TITLE
ready callback causing infinite loop when having multiple instance

### ISSUE THREAD

**Issue by MeKarina** [kadirahq/subs-manager#69]
i have this event...

```
Template.myTemplate.events({
  'focus input': function (e, t) {
  	if (t.data.comingFrom === 'A') {
      var h = Subs.subscribe('A');
      Tracker.autorun(function () {
        if (h.ready()) {
          t.f.set(A.find({}, {fields: {title:1}, reactive:false}).fetch())
          console.log(t.f.get())
        }
      });
    } else if (t.data.comingFrom === 'B') {
      var h = Subs.subscribe('B');
      Tracker.autorun(function () {
        if (h.ready()) {
          t.f.set(B.find({}, {fields: {title:1, src:1}, reactive:false}).fetch())
          console.log(t.f.get())
        }
      });
    }
  }
})
```
t.data.comingFrom based on this...
https://forums.meteor.com/t/how-do-i-get-template-name/15107/2

1. when i focus to instance A,,, as expected,, log show array of `A.find({}, {fields: {title:1}, reactive:false}).fetch()`
2. when i focus to instance B,, as expected,, log show array of `B.find({}, {fields: {title:1, src:1}, reactive:false}).fetch()`
3. However,, when i back to instance A,,, log show infinite loop.... i should force quit my chrome to stop infinite loop

however,, all is good without infinite loop when i use `Meteor.subscribe`...
```
Template.myTemplate.events({
  'focus input': function (e, t) {
  	if (t.data.comingFrom === 'A') {
      Meteor.subscribe('A', {
        onReady: function () {
          t.f.set(A.find({}, {fields: {title:1}, reactive:false}).fetch())
          console.log(t.f.get())
        }
      });
    } else if (t.data.comingFrom === 'B') {
      Meteor.subscribe('B', {
        onReady: function () {
          t.f.set(B.find({}, {fields: {title:1, src:1}, reactive:false}).fetch())
          console.log(t.f.get())
        }
      });
    }
  }
})
```

thank Youu...

**Comment by peterchoo** [comment]
It looks to me like your issue here is more that you are subscribing and running a Tracker.autorun inside an event.  I would structure this differently, and I would remove the dependency on the template name and instead just pass in a flag for the "type".

```javascript
// in your including template
{{> myTemplate type="A"}}
```

```javascript
Template.myTemplate.onCreated(function() {
  var self = this;

  // So we can refer to the collections
  self.subMap = {
    "A": {
      collection: A,
      fields: {title: 1}
    },
    "B":  {
      collection: B,
      fields: {title: 1, src: 1}
    },
  };

  // Cache static version (Does this need to be non-reactive?)
  self.result = new ReactiveVar([]); // initialise with empty array

  // Handle for subscription
  self.handle = Subs.subscribe(self.data.type); // uses what you passed in, you should error check this and make sure it is set

  // Track subscription ready status
  self.autorun(function() {
    if (self.handle.ready()) {
      self.result.set(
        self.subMap[self.data.type].collection.find({}, {
          fields: self.subMap[self.data.type].fields,
          reactive: false
        }).fetch()
      ); // Set the required collection's data to the template's reactive-var
    }
  });
});

Template.myTemplate.helpers({
  // Uses the reactive var we set up
  getStaticData: function() {
    var template = Template.instance();
    return template.result.get();
 },

  // Alternative which uses the collections directly and has reactivity
  getReactiveData: function() {
    var template = Template.instance();
    return template.subMap[template.data.type].collection.find({}, {
      fields: template.subMap[template.data.type].fields,
      reactive: false
    });
 },
});
```

**Comment by robfallows** [comment]
The real issue here is that you are `set`ting and `get`ing your ReactiveVar inside an autorun.

The behaviour of an autorun is to always run the function once (the first time you focus on each of the A and B inputs it runs once). Following this, an autorun will re-run if the following conditions are met:

1. The previous computation is invalidated:

   In your example, doing a `set` of an array to a ReactiveVar will always invalidate the computation unless you have provided an `equalsFunc` when defining the ReactiveVar (and this will be almost impossible for an array of any size). Check [the docs](http://docs.meteor.com/#/full/reactivevar) for more information.

2. A reactive data source is "read" within the autorun:

   In this case you are `get`ting the same ReactiveVar you have just `set`.

What this means is that the autorun will be re-run in order to satisfy the associated `get` - which does another `set`, which causes another re-run, and so on ...

I call this **reactive runaway**.

You can demonstrate this by making the following change to your code:

```javascript
Template.myTemplate.events({
  'focus input': function (e, t) {
    if (t.data.comingFrom === 'A') {
      var h = Subs.subscribe('A');
      Tracker.autorun(function () {
        if (h.ready()) {
          var aStuff = A.find({}, {fields: {title:1}, reactive:false}).fetch();
          t.f.set(aStuff);
          console.log(aStuff);
        }
      });
    } else if (t.data.comingFrom === 'B') {
      var h = Subs.subscribe('B');
      Tracker.autorun(function () {
        if (h.ready()) {
          var bStuff = B.find({}, {fields: {title:1}, reactive:false}).fetch();
          t.f.set(bStuff);
          console.log(bStuff);
        }
      });
    }
  }
})
```
The `get`s have been removed from the autoruns. You may safely put these into your template helpers for rendering.

**Comment by MeKarina** [comment]
thank You all and yes this is my own issue,,, thank You for the correction...
